### PR TITLE
Add support for https and prefix path

### PR DESCRIPTION
**Pull request by gedejong**
This PR introduces:

* https connections (properly)
* path prefix (when influxdb is behind a transparent proxy, this comes in use)
* documentation updates

### CODE REVIEW

**Comment by mvadu** [comment]
@gedejong do you mind submitting it to my version of this library https://github.com/mvadu/influxdbr2 ? @dleutnant seems to be busy with other things, and none of the PRs have been merged since Oct 2016.

**Comment by dleutnant** [comment]
@gedejong Thanks for your PR. I'll have a look on that later (together with the other PRs).

**Comment by gedejong** [comment]
@mvadu I'll wait for a response from dleutnant. Meanwhile, you can always do sth like this:

```
git remote add gedejong-origin https://github.com/gedejong/influxdbr
git pull gedejong-origin master
git push origin master
```
from the top of my head, this should merge my commit into your master branch and push the changes back to your repo. It will preserve commit author, date and committer. It might introduce merge conflicts because you've made similar changes. In that case, you can undo your commit first with:

```
git reset --hard 'HEAD^'
```
then do the above actions and you'll have to force your push with  `git push -f origin master` (don't usually do this, it's a very risky command).

Another solution is to keep your commits in history, but revert your commit.

**Comment by dleutnant** [comment]
Just to let you know that I'm currently working on integrating all PR into the new branch "prepare_cran"

**Comment by dleutnant** [comment]
PR is now integrated in [dleutnant/prepare_cran](https://github.com/dleutnant/influxdbr/tree/prepare_cran)

**Pull request closed without merging**
