### PR TITLE
add https support

### PR DESCRIPTION
**Pull request by retorquere**

### CODE REVIEW

**Comment by mvadu** [comment]
@retorquere I am not sure if @dleutnant is still maintaining this repo. My pull #2 is still open after a month. Hence I went ahead and published my own repo as [influxdbr2](https://github.com/mvadu/influxdbr2). You are welcome to send this PR on that repo, and I will be glad to merge.

**Comment by dleutnant** [comment]
Hi @mvadu and @retorquere ! Thanks for your comment and your pull! I've been quite busy on other things but will continue to work on the influxdbr package. So each PR is welcome!

**Comment by gedejong** [comment]
@dleutnant perhaps you can find some time to update the library? It seems a pretty trivial PR and would save us all some time.

**Comment by gedejong** [comment]
This PR misses some points where http is still being used. Please use https://github.com/dleutnant/influxdbr/pull/9 instead.

**Comment by retorquere** [comment]
No issue with using #9 instead of this.

**Pull request closed without merging**
